### ISSUE TITLE
کند بودن اتمام فرایند اسکن

### ISSUE THREAD

**Issue by navid221** [SafaSafari/ss-cloud-scanner#9]
سلام. این اسکریپت با هر بار اجرا کل رنج cf رو اسکن میکنه؟ خیلی طول میکشه تا  اسکن تموم بشه. طبیعیه؟
و اینکه نمیشه یه رنج دلخواه رو داد؟

**Comment by pedram795** [comment]
اسکن روی حالت vmess  حدود 1 ساعتی طول کشید و در نهایت با خطاهای ذیل مواجه شدم:

11:23:09: Nice :)))

Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000001E85C289700>
Traceback (most recent call last):
  File "C: ..\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C: ..\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C: ..\lib\asyncio\base_events.py", line 751, in call_soon
    self._check_closed()
  File "C: ..\lib\asyncio\base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000001E85C289700>
Traceback (most recent call last):
  File "C: ..\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C: ..\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C: ..\lib\asyncio\base_events.py", line 751, in call_soon
    self._check_closed()
  File "C: ..\lib\asyncio\base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed

**Comment by SafaSafari** [comment]
> سلام. این اسکریپت با هر بار اجرا کل رنج cf رو اسکن میکنه؟ خیلی طول میکشه تا اسکن تموم بشه. طبیعیه؟ و اینکه نمیشه یه رنج دلخواه رو داد؟

بله طبیعی هست
و این که این برنامه فقط ۵ آیپی اول هر رنج رو تست می‌کنه و سرعتش اینجوریه
کل آیپی ها رو اسکن کنه به یک شبانه روز هم شاید برسه😂
تعداد رنج های کلادفلر بسیار زیاده

ارور هم متاسفانه ویندوز ندارم که تست کنم
ولی اگه فرآیند اسکن انجام شده و آیپی ای چاپ نکرده، یعنی آیپی سالمی روی اون اپراتور وجود نداره
